server.servlet.contextPath=/api
#management.endpoints.web.exposure.include=*

# enable devtools defaults
spring.devtools.add-properties=true

spring.main.banner-mode=off

spring.datasource.url=jdbc:postgresql://localhost/searobin?currentschema=searobin
spring.datasource.username=postgres
spring.datasource.password=superpostgres

# debug=true